name: push

on:
  push:

env:
  LATEST_TAG: ozhogincode/devops-for-programmers-project-74:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: ls -la

      - name: Test
        run: |
          docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.LATEST_TAG }}